# services/agent/routing/keywords.py

from services.agent.routing.hebrew_norm import _normalize_keyword_set

_CONVERSATIONAL_KEYWORDS: tuple[str, ...] = (
    # ברכות ושיח חברתי (קצרים, חד-משמעיים)
    "שלום",
    "היי",
    "בוקר טוב",
    "ערב טוב",
    "לילה טוב",
    # זהות (תשובה קצרה מה-IDENTITY)
    "מי אתה",
    "מי את",
    "אתה מי",
    # שיח קצר
    "מה שלומך",
    "מה קורה",
    "מה נשמע",
    "מה המצב",
    "איך הולך",
    "איך קוראים",
    "מה שמך",
    "מה השם",
    # סיום שיחה
    "תודה",
    "תודה רבה",
    "אוקיי",
    "בסדר",
    "ביי",
    "להתראות",
    "נתראה",
    # אנגלית
    "hello",
    "hey",
    "who are you",
    "thanks",
    "thank you",
    "bye",
    "goodbye",
    "see you",
)

# שאלות יכולות — חובה לעבור למסלול מלא עם כלים
_CAPABILITY_PATTERNS: tuple[str, ...] = (
    "מה אתה יכול",
    "מה את יכול",
    "מה אפשר",
    "במה אתה יכול",
    "רשימת כלים",
    "איזה כלים",
    "אילו כלים",
    "רשימת סקילים",
    "רשימת הסקילים",
    "מה היכולות",
    "מה יכולותיך",
    "במה תוכל",
    "תפרט את הכלים",
    "תפרט את הסקילים",
    "תפרט כלים",
    "תפרט סקילים",
    "תן רשימת כלים",
    "תן רשימת סקילים",
    # NOTE: Removed overly generic patterns that caused false positives
    # when skill results were appended to the agent prompt:
    #   "פרט" — matches פרטי/פרטים/פרטי המבקש in skill output
    #   "help" — matches English text in skill output
    #   "skills" — matches English text in skill output
    #   "capabilities" — matches English text in skill output
    #   "סקילים" (bare) — too generic, use "רשימת סקילים" instead
    #   "עזרה" — can appear in skill output
    #   "תפרט" (bare) — use "תפרט את הכלים" instead
    #   "תן רשימה" (bare) — use "תן רשימת כלים" instead
)

_SYSTEM_KEYWORDS: tuple[str, ...] = (
    # Hebrew
    "מערכת",
    "שרת",
    "שרתים",
    "רשת",
    "תהליך",
    "זיכרון",
    "CPU",
    "מעבד",
    "GPU",
    "כרטיס גרפי",
    "דיסק",
    "קובץ",
    "קבצים",
    "IP",
    "כתובת",
    "פורט",
    "שירות",
    "תהליכים",
    "התראה",
    "אזהרה",
    "חיבור",
    "חיבורים",
    "משימה",
    "משימות",
    "מנהל",
    "מנהלת",
    "הרשאה",
    "הרשאות",
    "סיסמה",
    "סיסמאות",
    "אבטחה",
    "אבטחת",
    "מוניטור",
    "ניטור",
    "סריקה",
    "סרוק",
    "בדיקה",
    "בדוק",
    "מצב",
    "מצבים",
    "מידע",
    "נתונים",
    "משתמש",
    "משתמשים",
    "התחברות",
    "התחבר",
    "מכשיר",
    "מכשירים",
    "LAN",
    "סטארטאפ",
    "היסטוריה",
    "PowerShell",
    "פקודה",
    "פקודות",
    "קוד",
    "קודים",
    "סודי",
    "סוד",
    "תיקייה",
    "תיקיות",
    "חיפוש",
    "hash",
    "IOC",
    "חסימה",
    "חסום",
    "ניהול",
    "Sentinel",
    "אירוע",
    "אירועים",
    "תור",
    "Telegram",
    "זיווג",
    "הודעה",
    "הודעות",
    "חדשות",
    "עיתון",
    "ניתוח",
    "אינטל",
    "screenshot",
    "צילום מסך",
    "thinking",
    "חשיבה",
    "action",
    "פעולה",
    "פעולות",
    "אישור",
    "ביטול",
    "מפתח",
    "מפתחות",
    "הצפנה",
    "הצפן",
    "פענוח",
    "פענח",
    # English
    "memory",
    "alert",
    "cpu",
    "gpu",
    "disk",
    "file",
    "files",
    "port",
    "ports",
    "service",
    "services",
    "process",
    "processes",
    "connection",
    "connections",
    "network",
    "firewall",
    "security",
    "monitor",
    "scan",
    "check",
    "status",
    "info",
    "data",
    "user",
    "users",
    "device",
    "devices",
    "lan",
    "startup",
    "history",
    "powershell",
    "command",
    "commands",
    "directory",
    "folder",
    "search",
    "hash",
    "ioc",
    "block",
    "blocked",
    "manage",
    "sentinel",
    "event",
    "events",
    "queue",
    "telegram",
    "pairing",
    "message",
    "messages",
    "news",
    "digest",
    "analyze",
    "intel",
    "screenshot",
    "thinking",
    "action",
    "approve",
    "deny",
    "code",
    "codes",
    "secret",
    "key",
    "keys",
    "encrypt",
    "decrypt",
)

# ── Pre-computed normalized keyword sets (built once at import) ───────────
# These tuples include BOTH the original lowercased forms and the
# Hebrew-prefix-stripped forms, so a single substring scan catches both
# "המערכת" (raw) and "מערכת" (stem).
_CONVERSATIONAL_KEYWORDS_NORM: tuple[str, ...] = _normalize_keyword_set(_CONVERSATIONAL_KEYWORDS)
_CAPABILITY_PATTERNS_NORM: tuple[str, ...] = _normalize_keyword_set(_CAPABILITY_PATTERNS)
_SYSTEM_KEYWORDS_NORM: tuple[str, ...] = _normalize_keyword_set(_SYSTEM_KEYWORDS)

# Strict greeting set — these phrases mean "hello / how are you" and
# should ONLY trigger conversational mode when the query is essentially
# JUST the greeting (no system noun follows). Used by _is_conversational
# under tighter conditions than the broad _CONVERSATIONAL_KEYWORDS scan.
_STRICT_GREETING_PHRASES: tuple[str, ...] = _normalize_keyword_set(
    ("מה המצב", "מה קורה", "מה נשמע", "בוקר טוב", "מה שלומך")
)
