# services/agent/skill_keyword_triggers.py
"""Additional skill keyword triggers — context-specific, system/security,
translation, file analysis, web scraping, report maker.

Extracted from skill_keywords.py (SRP). Merged into _SKILL_KEYWORD_MAP at
import time to maintain backward compatibility.
"""

_SKILL_KEYWORD_TRIGGERS: dict[str, set] = {
    # ── General trigger words ────────────────────────────────────────────────────
    "איפה": {"skill_geocode-skill"},
    # ── Context-specific triggers ───────────────────────────────────────────────
    "תזמין": {"skill_geocode-skill"},
    "זמן": {"skill_geocode-skill", "skill_weather-skill"},
    "שעה": {"skill_weather-skill"},
    "מסלול": {"skill_geocode-skill"},
    "מכונית": {"skill_geocode-skill"},
    "אוטו": {"skill_geocode-skill"},
    "רכבת": {"skill_geocode-skill"},
    "אוטובוס": {"skill_geocode-skill"},
    "תחבורה": {"skill_geocode-skill"},
    "טיסה": {"skill_geocode-skill"},
    "שדה תעופה": {"skill_geocode-skill"},
    "נמל תעופה": {"skill_geocode-skill"},
    "טיול": {"skill_geocode-skill"},
    "לטייל": {"skill_geocode-skill"},
    "לנסוע": {"skill_geocode-skill"},
    "ללכת": {"skill_geocode-skill"},
    "מגיע": {"skill_geocode-skill"},
    "מגיעה": {"skill_geocode-skill"},
    "הגעה": {"skill_geocode-skill"},
    "יציאה": {"skill_geocode-skill"},
    "הגענו": {"skill_geocode-skill"},
    "נוסע": {"skill_geocode-skill"},
    "נוסעת": {"skill_geocode-skill"},
    "נוסעים": {"skill_geocode-skill"},
    # ── System & Security triggers ──────────────────────────────────────────────
    "אבטחה": {"skill_firewall-skill", "skill_intel-skill"},
    "הגנה": {"skill_firewall-skill", "skill_intel-skill"},
    "חסימה": {"skill_firewall-skill"},
    "פתח": {"skill_firewall-skill"},
    "גישה": {"skill_firewall-skill", "skill_intel-skill"},
    "חדירה": {"skill_firewall-skill", "skill_intel-skill"},
    "פריצה": {"skill_firewall-skill", "skill_intel-skill"},
    "זיהום": {"skill_intel-skill"},
    "תולעת": {"skill_intel-skill"},
    "סוס טרויאני": {"skill_intel-skill"},
    "malware": {"skill_intel-skill"},
    "טroyan": {"skill_intel-skill"},
    "רושע": {"skill_intel-skill"},
    "איום": {"skill_firewall-skill", "skill_intel-skill"},
    "סכנה": {"skill_firewall-skill", "skill_intel-skill"},
    "התקפה": {"skill_firewall-skill", "skill_intel-skill"},
    "התראה": {"skill_report-maker"},
    "התרעה": {"skill_report-maker"},
    "שרת חשוד": {"skill_intel-skill"},
    "שרת זדוני": {"skill_intel-skill"},
    "רשת": {"skill_firewall-skill", "skill_intel-skill"},
    "נטוורק": {"skill_firewall-skill", "skill_intel-skill"},
    "ports": {"skill_firewall-skill"},
    "פורטים": {"skill_firewall-skill"},
    "חיבורים": {"skill_firewall-skill"},
    "חיבור": {"skill_firewall-skill"},
    "תעבורה": {"skill_firewall-skill"},
    "תקשורת": {"skill_firewall-skill"},
    "תעבורת רשת": {"skill_firewall-skill"},
    "log": {"skill_report-maker"},
    "לוג": {"skill_report-maker"},
    "לוגים": {"skill_report-maker"},
    "אירוע": {"skill_report-maker"},
    "אירועים": {"skill_report-maker"},
    # ── Translation triggers ────────────────────────────────────────────────────
    "מה כתוב": {"skill_translator-skill", "skill_file-analyst"},
    "מה רשום": {"skill_translator-skill", "skill_file-analyst"},
    "תקרא": {"skill_translator-skill", "skill_file-analyst"},
    "קרא": {"skill_translator-skill", "skill_file-analyst"},
    "תפרט": {"skill_file-analyst"},
    "פרט": {"skill_file-analyst"},
    "תסכם": {"skill_file-analyst"},
    "תנסח": {"skill_file-analyst", "skill_translator-skill"},
    "תתרגם": {"skill_translator-skill"},
    "לעברית": {"skill_translator-skill"},
    "לאנגלית": {"skill_translator-skill"},
    "מאנגלית": {"skill_translator-skill"},
    "מעברית": {"skill_translator-skill"},
    "שפה": {"skill_translator-skill"},
    "לשפה": {"skill_translator-skill"},
    " translate": {"skill_translator-skill"},
    "translation": {"skill_translator-skill"},
    # ── File analysis triggers ─────────────────────────────────────────────────
    "מסמכים": {"skill_file-analyst"},
    "docx": {"skill_file-analyst"},
    "xlsx": {"skill_file-analyst"},
    "json": {"skill_file-analyst"},
    "md": {"skill_file-analyst"},
    "markdown": {"skill_file-analyst"},
    "נתונים": {"skill_file-analyst"},
    "table": {"skill_file-analyst"},
    "טבלה": {"skill_file-analyst"},
    "תמונות": {"skill_file-analyst"},
    "image": {"skill_file-analyst"},
    "jpg": {"skill_file-analyst"},
    "jpeg": {"skill_file-analyst"},
    "png": {"skill_file-analyst"},
    "gif": {"skill_file-analyst"},
    "bmp": {"skill_file-analyst"},
    "webp": {"skill_file-analyst"},
    "scan": {"skill_file-analyst"},
    "סריקה": {"skill_file-analyst"},
    "מצולם": {"skill_file-analyst"},
    "חתום": {"skill_file-analyst"},
    "חתימה": {"skill_file-analyst"},
    "לקרוא": {"skill_file-analyst"},
    "לתרגם": {"skill_translator-skill"},
    "לנתח": {"skill_file-analyst"},
    "להמיר": {"skill_file-analyst"},
    "להוריד": {"skill_web-scraper"},
    "להורדה": {"skill_web-scraper"},
    "download": {"skill_web-scraper"},
    # ── Web scraping additional triggers ─────────────────────────────────────────
    "website": {"skill_web-scraper"},
    "article": {"skill_web-scraper"},
    "כתבה": {"skill_web-scraper"},
    "מאמר": {"skill_web-scraper"},
    "extract": {"skill_web-scraper"},
    "extract data": {"skill_web-scraper"},
    "חלץ": {"skill_web-scraper"},
    "חילוץ": {"skill_web-scraper"},
    "לחלץ": {"skill_web-scraper"},
    "google": {"skill_web-scraper"},
    "bing": {"skill_web-scraper"},
    "yahoo": {"skill_web-scraper"},
    "duckduckgo": {"skill_web-scraper"},
    "wikipedia": {"skill_web-scraper"},
    "ויקיפדיה": {"skill_web-scraper"},
    "imdb": {"skill_web-scraper"},
    "youtube": {"skill_web-scraper"},
    "יוטיוב": {"skill_web-scraper"},
    "amazon": {"skill_web-scraper"},
    "אמזון": {"skill_web-scraper"},
    "ebay": {"skill_web-scraper"},
    "איביי": {"skill_web-scraper"},
    "מחירים": {"skill_web-scraper"},
    "price": {"skill_web-scraper"},
    "cost": {"skill_web-scraper"},
    "עלות": {"skill_web-scraper"},
    "compare": {"skill_web-scraper"},
    "השווה": {"skill_web-scraper"},
    "השוואה": {"skill_web-scraper"},
    "comparison": {"skill_web-scraper"},
    "דירוג": {"skill_web-scraper"},
    "rating": {"skill_web-scraper"},
    "ביקורת": {"skill_web-scraper"},
    "review": {"skill_web-scraper"},
    "reviews": {"skill_web-scraper"},
    # ── Report maker additional triggers ───────────────────────────────────────
    "create report": {"skill_report-maker"},
    "generate report": {"skill_report-maker"},
    "documentation": {"skill_report-maker"},
    "pdf report": {"skill_report-maker"},
    "word report": {"skill_report-maker"},
    "docx report": {"skill_report-maker"},
    "analysis report": {"skill_report-maker"},
    "summary report": {"skill_report-maker"},
    "briefing": {"skill_report-maker"},
    "status update": {"skill_report-maker"},
    "עדכונים": {"skill_report-maker"},
    "סטטוס": {"skill_report-maker"},
    "תיאור מצב": {"skill_report-maker"},
    "סיכום מצב": {"skill_report-maker"},
    "מצב כללי": {"skill_report-maker"},
    "מצב הבוט": {"skill_report-maker"},
    "מצב הסוכן": {"skill_report-maker"},
}
