# services/agent/skill_keywords.py

_SKILL_KEYWORD_MAP: dict[str, set] = {
    # ── news-monitor ────────────────────────────────────────────────────────────
    "news": {"skill_news-monitor"},
    "חדשות": {"skill_news-monitor"},
    "מבזקים": {"skill_news-monitor"},
    "בישראל": {"skill_news-monitor"},
    "מה קורה": {"skill_news-monitor"},
    "מה נשמע": {"skill_news-monitor"},
    "politics": {"skill_news-monitor"},
    "פוליטיקה": {"skill_news-monitor"},
    "ממשלה": {"skill_news-monitor"},
    "כנסת": {"skill_news-monitor"},
    "economy": {"skill_news-monitor", "skill_stocks-skill", "skill_currency-skill"},
    # ── currency-skill ──────────────────────────────────────────────────────────
    "כסף": {"skill_currency-skill"},
    "דולר": {"skill_currency-skill"},
    "שער": {"skill_currency-skill"},
    "מטבע": {"skill_currency-skill"},
    "המרה": {"skill_currency-skill"},
    "יורו": {"skill_currency-skill"},
    "שקל": {"skill_currency-skill"},
    "לשקל": {"skill_currency-skill"},
    "לדולר": {"skill_currency-skill"},
    "כמה שווה": {"skill_currency-skill"},
    "exchange": {"skill_currency-skill"},
    # ── missing currency names ──
    "פורינט": {"skill_currency-skill"},
    "פורניט": {"skill_currency-skill"},
    "לירה": {"skill_currency-skill"},
    "רנד": {"skill_currency-skill"},
    "רובל": {"skill_currency-skill"},
    "ין": {"skill_currency-skill"},
    "וון": {"skill_currency-skill"},
    # ── weather-skill ───────────────────────────────────────────────────────────
    "מזג": {"skill_weather-skill"},
    "weather": {"skill_weather-skill"},
    "תחזית": {"skill_weather-skill"},
    "אוויר": {"skill_weather-skill"},
    "טמפרטורה": {"skill_weather-skill"},
    "גשם": {"skill_weather-skill"},
    "לחות": {"skill_weather-skill"},
    "רוח": {"skill_weather-skill"},
    "קור": {"skill_weather-skill"},
    "חום": {"skill_weather-skill"},
    # ── stocks-skill ────────────────────────────────────────────────────────────
    "סטוק": {"skill_stocks-skill"},
    "בורסה": {"skill_stocks-skill"},
    "מניה": {"skill_stocks-skill"},
    "מחיר": {"skill_stocks-skill", "skill_web-scraper"},
    "ערך": {"skill_stocks-skill"},
    "טיקר": {"skill_stocks-skill"},
    "מניות": {"skill_stocks-skill"},
    # ── crypto currencies (route to stocks-skill) ──
    "ביטקוין": {"skill_stocks-skill"},
    "bitcoin": {"skill_stocks-skill"},
    "btc": {"skill_stocks-skill"},
    "אתריום": {"skill_stocks-skill"},
    "ethereum": {"skill_stocks-skill"},
    "eth": {"skill_stocks-skill"},
    "קריפטו": {"skill_stocks-skill"},
    "coin": {"skill_stocks-skill"},
    # ── translator-skill ──────────────────────────────────────────────────────────
    "תרגם": {"skill_translator-skill"},
    "translate": {"skill_translator-skill"},
    "תרגום": {"skill_translator-skill"},
    # ── geocode-skill ────────────────────────────────────────────────────────────
    "geocode": {"skill_geocode-skill"},
    "מרחק": {"skill_geocode-skill"},
    "נסיעה": {"skill_geocode-skill"},
    "דרך": {"skill_geocode-skill"},
    "כתובת": {"skill_geocode-skill", "skill_intel-skill"},
    "מיקום": {"skill_geocode-skill"},
    "מפה": {"skill_geocode-skill"},
    # ── firewall-skill ───────────────────────────────────────────────────────────
    "firewall": {"skill_firewall-skill"},
    "חומת אש": {"skill_firewall-skill"},
    "block": {"skill_firewall-skill"},
    "unblock": {"skill_firewall-skill"},
    "חסום": {"skill_firewall-skill"},
    "שחרר": {"skill_firewall-skill"},
    # ── intel-skill ─────────────────────────────────────────────────────────────
    "ip": {"skill_intel-skill"},
    "אייפי": {"skill_intel-skill"},
    "domain": {"skill_intel-skill"},
    "דומיין": {"skill_intel-skill"},
    "hash": {"skill_intel-skill", "skill_crypto-skill"},
    "whois": {"skill_intel-skill"},
    "dns": {"skill_intel-skill"},
    "reputation": {"skill_intel-skill"},
    "מוניטין": {"skill_intel-skill"},
    "חשד": {"skill_intel-skill"},
    "בדיקת אייפי": {"skill_intel-skill"},
    "בדיקת דומיין": {"skill_intel-skill"},
    "כתובת אייפי": {"skill_intel-skill"},
    "בדוק אייפי": {"skill_intel-skill"},
    "זדוני": {"skill_intel-skill"},
    "וירוס": {"skill_intel-skill"},
    "תוכנה זדונית": {"skill_intel-skill"},
    # ── crypto-skill ────────────────────────────────────────────────────────────
    "sha256": {"skill_crypto-skill"},
    "md5": {"skill_crypto-skill"},
    "jwt": {"skill_crypto-skill"},
    "password": {"skill_crypto-skill"},
    "uuid": {"skill_crypto-skill"},
    "hmac": {"skill_crypto-skill"},
    "crypto": {"skill_stocks-skill", "skill_crypto-skill"},
    "הצפנה": {"skill_crypto-skill"},
    "גיבוב": {"skill_crypto-skill"},
    "סיסמה": {"skill_crypto-skill"},
    "base64": {"skill_crypto-skill"},
    "decode": {"skill_crypto-skill"},
    "פענח": {"skill_crypto-skill"},
    "קידוד": {"skill_crypto-skill"},
    "אקראי": {"skill_crypto-skill"},
    "צור סיסמה": {"skill_crypto-skill"},
    # ── report-maker ────────────────────────────────────────────────────────────
    "report": {"skill_report-maker"},
    "דוח": {"skill_report-maker"},
    "דוחות": {"skill_report-maker"},
    "מסמך": {"skill_report-maker"},
    "דווח": {"skill_report-maker"},
    "מצב מערכת": {"skill_report-maker"},
    # ── web-scraper ─────────────────────────────────────────────────────────────
    "scrape": {"skill_web-scraper"},
    "גרד": {"skill_web-scraper"},
    "אתר": {"skill_web-scraper"},
    "url": {"skill_web-scraper"},
    "אינטרנט": {"skill_web-scraper"},
    "דף": {"skill_web-scraper"},
    "html": {"skill_web-scraper"},
    "web": {"skill_web-scraper"},
    # ── file-analyst ───────────────────────────────────────────────────────────
    "file": {"skill_file-analyst"},
    "pdf": {"skill_file-analyst"},
    "ocr": {"skill_file-analyst"},
    "screenshot": {"skill_file-analyst"},
    "קובץ": {"skill_file-analyst"},
    "קבצים": {"skill_file-analyst"},
    "ניתוח": {"skill_file-analyst"},
    "נתח": {"skill_file-analyst"},
    "תמונה": {"skill_file-analyst"},
    "סכם": {"skill_file-analyst"},
    "סיכום": {"skill_file-analyst"},
    "חוזה": {"skill_file-analyst"},
    "שכירות": {"skill_file-analyst"},
    "הסכם": {"skill_file-analyst"},
    "word": {"skill_file-analyst"},
    "excel": {"skill_file-analyst"},
    "csv": {"skill_file-analyst"},
    "txt": {"skill_file-analyst"},
    "טקסט": {"skill_file-analyst"},
    # ── pcap-analyst ────────────────────────────────────────────────────────────
    "pcap": {"skill_pcap-analyst"},
    "pcapng": {"skill_pcap-analyst"},
    "capture": {"skill_pcap-analyst"},
    "traffic dump": {"skill_pcap-analyst"},
    "network capture": {"skill_pcap-analyst"},
    "packet": {"skill_pcap-analyst"},
    "wireshark": {"skill_pcap-analyst"},
    "dns queries": {"skill_pcap-analyst"},
    "tls sni": {"skill_pcap-analyst"},
    "תעבורת רשת": {"skill_pcap-analyst"},
    "לכידת רשת": {"skill_pcap-analyst"},
    "פקטות": {"skill_pcap-analyst"},
    "ניתוח רשת": {"skill_pcap-analyst"},
    # ── email-forensics ─────────────────────────────────────────────────────────
    "eml": {"skill_email-forensics"},
    "phishing": {"skill_email-forensics"},
    "email forensics": {"skill_email-forensics"},
    "spf": {"skill_email-forensics"},
    "dkim": {"skill_email-forensics"},
    "dmarc": {"skill_email-forensics"},
    "email headers": {"skill_email-forensics"},
    "authentication results": {"skill_email-forensics"},
    "msg file": {"skill_email-forensics"},
    "outlook": {"skill_email-forensics"},
    "פישינג": {"skill_email-forensics"},
    "דואר זדוני": {"skill_email-forensics"},
    "ניתוח אימייל": {"skill_email-forensics"},
    "כותרות מייל": {"skill_email-forensics"},
    "אימות מייל": {"skill_email-forensics"},
    # ── persistence-hunter ──────────────────────────────────────────────────────
    "persistence": {"skill_persistence-hunter"},
    "autorun": {"skill_persistence-hunter"},
    "run key": {"skill_persistence-hunter"},
    "runonce": {"skill_persistence-hunter"},
    "startup folder": {"skill_persistence-hunter"},
    "wmi subscription": {"skill_persistence-hunter"},
    "wmi event": {"skill_persistence-hunter"},
    "scheduled task": {"skill_persistence-hunter", "skill_intel-skill"},
    "persistence scan": {"skill_persistence-hunter"},
    "baseline": {"skill_persistence-hunter"},
    "התמדה": {"skill_persistence-hunter"},
    "הפעלה אוטומטית": {"skill_persistence-hunter", "skill_file-analyst"},
    "רישום אוטומטי": {"skill_persistence-hunter"},
    "תיקיית הפעלה": {"skill_persistence-hunter"},
    "משימה מתוזמנת": {"skill_persistence-hunter"},
    "סריקת התמדה": {"skill_persistence-hunter"},
}


# Additional triggers extracted to skill_keyword_triggers.py (SRP)
from services.agent.skill_keyword_triggers import _SKILL_KEYWORD_TRIGGERS  # noqa: E402

# Merge additional triggers into the main keyword map
_SKILL_KEYWORD_MAP.update(_SKILL_KEYWORD_TRIGGERS)


# Semantic descriptions extracted to skill_descriptions.py (SRP)
from services.agent.skill_descriptions import _SKILL_DESCRIPTIONS  # noqa: E402,F401
